/*
 * Manage compute resources
 *
 * Servers management
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ServerRequest struct {
	// The server name
	Name string `json:"name"`
	// The server description
	Description string `json:"description,omitempty"`
}
