/*
 * Manage compute resources
 *
 * Servers management
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Error struct {
	// Failure status
	Status string `json:"status"`
	// Failure message
	Message string `json:"message"`
}
