/*
 * Manage compute resources
 *
 * Servers management
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServerRequest struct {
	// The server name
	Name string `json:"name"`
	// The server description
	Description string `json:"description,omitempty"`
}
